In [1]:
print("Hello AquaGuard 💧")

Hello AquaGuard 💧

In [3]:
import pandas as pd
import numpy as np

In [5]:
import pandas as pd
import numpy as np
import random

data = []

seasons = ["summer", "monsoon", "winter"]

for _ in range(1000):
    tank_capacity = random.randint(5000, 20000)
    current_level = random.randint(1000, tank_capacity)
    residents = random.randint(5, 50)
    
    base_usage = residents * random.uniform(120, 180)
    
    rainfall = random.uniform(0, 10)
    season = random.choice(seasons)
    
    if season == "summer":
        usage = base_usage * 1.2
    elif season == "monsoon":
        usage = base_usage * 0.9
    else:
        usage = base_usage
    
    usage = usage * (1 - rainfall * 0.02)
    
    days_left = current_level / usage
    
    data.append([
        tank_capacity,
        current_level,
        residents,
        usage,
        rainfall,
        season,
        round(days_left, 2)
    ])

df = pd.DataFrame(data, columns=[
    "tank_capacity",
    "current_level",
    "residents",
    "daily_usage",
    "rainfall",
    "season",
    "days_left"
])

df.to_csv("water_data.csv", index=False)

df.head(10)

,tank_capacity,current_level,residents,daily_usage,rainfall,season,days_left
0,10700,1018,36,4307.298198,6.478662,winter,0.24
1,12672,9100,50,6724.696205,7.484769,summer,1.35
2,8618,3725,19,2928.959925,7.045614,winter,1.27
3,5613,2537,24,3461.914197,8.365875,summer,0.73
4,12041,8849,28,3528.505924,6.299878,summer,2.51
5,8184,4730,28,4099.143248,6.476071,summer,1.15
6,11585,3853,13,2337.919423,5.367221,summer,1.65
7,15042,11360,42,4278.010627,7.094696,monsoon,2.66
8,11311,4610,38,4472.935681,7.001845,monsoon,1.03
9,9879,8417,22,3496.368388,6.201108,summer,2.41

In [6]:
df.describe()

,tank_capacity,current_level,residents,daily_usage,rainfall,days_left
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,12713.965000,7005.641000,27.976000,3881.624207,5.147733,2.807900
std,4318.504797,4248.320807,13.533535,2038.642050,2.879322,3.402469
min,5048.000000,1015.000000,5.000000,467.548211,0.000144,0.130000
25%,9070.000000,3714.500000,16.000000,2203.924990,2.725214,0.900000
50%,12866.000000,6033.000000,28.000000,3740.123715,5.339205,1.705000
75%,16517.750000,9883.000000,40.000000,5389.828872,7.625616,3.220000
max,19957.000000,19366.000000,50.000000,9869.820252,9.997389,29.160000

In [1]:
import os
os.getcwd()

'C:\\Users\\Edlyn Jessica\\Desktop\\GroundWater_Project'